FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=config.settings.production
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*
# Install python requirements
COPY requirements.txt /app/
COPY requirements/ /app/requirements/
RUN pip install --no-cache-dir -r requirements.txt
# Copy application files
COPY . /app/
# Collect static files
RUN python manage.py collectstatic --noinput
# Expose port
EXPOSE 8000
# Set entrypoint
ENTRYPOINT ["/app/docker/production/entrypoint.sh"]